//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Language", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t create new city..
        /// </summary>
        internal static string AddCityError {
            get {
                return ResourceManager.GetString("AddCityError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AlreadyBet {
            get {
                return ResourceManager.GetString("AlreadyBet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bid accepted..
        /// </summary>
        internal static string BidAccepted {
            get {
                return ResourceManager.GetString("BidAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bid error..
        /// </summary>
        internal static string BidError {
            get {
                return ResourceManager.GetString("BidError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bid not exist..
        /// </summary>
        internal static string BidNotExist {
            get {
                return ResourceManager.GetString("BidNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bid rejected..
        /// </summary>
        internal static string BidRejected {
            get {
                return ResourceManager.GetString("BidRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bid sent..
        /// </summary>
        internal static string BidSent {
            get {
                return ResourceManager.GetString("BidSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail already in use..
        /// </summary>
        internal static string EmailAlreadyInUse {
            get {
                return ResourceManager.GetString("EmailAlreadyInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email confirmation error..
        /// </summary>
        internal static string EmailConfirmError {
            get {
                return ResourceManager.GetString("EmailConfirmError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email confirmed..
        /// </summary>
        internal static string EmailConfirmSuccess {
            get {
                return ResourceManager.GetString("EmailConfirmSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail not exist..
        /// </summary>
        internal static string EmailNotExist {
            get {
                return ResourceManager.GetString("EmailNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string EmailSent {
            get {
                return ResourceManager.GetString("EmailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not image..
        /// </summary>
        internal static string ImageExtensionError {
            get {
                return ResourceManager.GetString("ImageExtensionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image size must be less then 2Mb..
        /// </summary>
        internal static string ImageSizeError {
            get {
                return ResourceManager.GetString("ImageSizeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect E-mail..
        /// </summary>
        internal static string IncorrectEmail {
            get {
                return ResourceManager.GetString("IncorrectEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Server Error..
        /// </summary>
        internal static string InternalError {
            get {
                return ResourceManager.GetString("InternalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticate before call this method..
        /// </summary>
        internal static string NotAuthenticated {
            get {
                return ResourceManager.GetString("NotAuthenticated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password changed..
        /// </summary>
        internal static string PasswordChanged {
            get {
                return ResourceManager.GetString("PasswordChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search no results found..
        /// </summary>
        internal static string SearchNoResults {
            get {
                return ResourceManager.GetString("SearchNoResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SelfBidError {
            get {
                return ResourceManager.GetString("SelfBidError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tour created..
        /// </summary>
        internal static string TourCreated {
            get {
                return ResourceManager.GetString("TourCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error on creating new tour..
        /// </summary>
        internal static string TourCreatingError {
            get {
                return ResourceManager.GetString("TourCreatingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tour deleted..
        /// </summary>
        internal static string TourDeleted {
            get {
                return ResourceManager.GetString("TourDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tour has been expired..
        /// </summary>
        internal static string TourExpiredError {
            get {
                return ResourceManager.GetString("TourExpiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tour not found..
        /// </summary>
        internal static string TourNotExist {
            get {
                return ResourceManager.GetString("TourNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tour updated..
        /// </summary>
        internal static string TourUpdated {
            get {
                return ResourceManager.GetString("TourUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error on updating tour..
        /// </summary>
        internal static string TourUpdatingError {
            get {
                return ResourceManager.GetString("TourUpdatingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found..
        /// </summary>
        internal static string UserNotExist {
            get {
                return ResourceManager.GetString("UserNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User profile not exist..
        /// </summary>
        internal static string UserProfileNotExist {
            get {
                return ResourceManager.GetString("UserProfileNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User profile updated..
        /// </summary>
        internal static string UserProfileUpdated {
            get {
                return ResourceManager.GetString("UserProfileUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User registered..
        /// </summary>
        internal static string UserRegistered {
            get {
                return ResourceManager.GetString("UserRegistered", resourceCulture);
            }
        }
    }
}
